-- Wander Eire: second content batch - 10 iconic + 10 hidden-gem free locations.
-- Safe to run any time after next-step.sql (uses the same admin policies and the `facts` column).
-- Re-running this file is also safe (upserts by id).

insert into public.locations
  (id, name, county, category, latitude, longitude, cost, distance, kicker, description, address, parking, facts)
values
  -- ==================== ICONIC (10) ====================
  (8, 'Giant’s Causeway', 'Antrim', 'viewpoint', 55.2408, -6.5116, 'Free (paid visitor centre parking)', '1 mile return', '40,000 basalt columns on the Causeway Coast', 'Walk out onto the hexagonal stones formed by an ancient volcanic eruption, with myth attributing them to the giant Finn McCool. The clifftop path gives free access to the stones without going through the visitor centre.', 'Giant’s Causeway, Bushmills, Co. Antrim, BT57 8SU', 'Paid National Trust visitor-centre parking; free roadside and clifftop-path alternatives nearby.', array['UNESCO World Heritage', '40,000 columns', 'Coastal path']),
  (9, 'Poulnabrone Dolmen', 'Clare', 'historic', 53.0083, -9.1439, 'Free', '5 min walk from car park', 'A 5,000-year-old portal tomb on the Burren’s limestone pavement', 'One of Ireland’s oldest and most photographed monuments, standing alone on exposed karst limestone. Excavations found the remains of over 30 people beneath the capstone.', 'Poulnabrone, Co. Clare', 'Free roadside car park on the R480.', array['Neolithic, c. 3800 BC', 'Roadside access', 'Open all year']),
  (10, 'Mussenden Temple & Downhill Demesne', 'Derry', 'viewpoint', 55.1662, -6.8215, 'Free (paid NT parking, or free at Bishop’s Gate)', '1.5 km of grounds', 'A cliff-edge library modelled on an Italian temple', 'This 18th-century rotunda, built as a library for an eccentric bishop, sits close enough to the cliff edge that it looks ready to fall in. The demesne’s ruined mansion and gardens spread out behind it above the Atlantic.', 'Downhill Demesne, Mussenden Road, Castlerock, Co. Derry~Londonderry, BT51 4RP', 'National Trust car park charges a fee; free parking further along the A2 at Bishop’s Gate.', array['Built 1785', 'Clifftop setting', 'National Trust']),
  (11, 'Keem Bay', 'Mayo', 'beach', 53.9727, -10.2144, 'Free (pay & display fills early in summer)', 'Roadside cove', 'Ireland’s most-loved beach, ringed by cliffs', 'A horseshoe of white sand at the western tip of Achill Island, hemmed in by steep green cliffs on three sides and the open Atlantic on the fourth. Regularly voted Ireland’s best beach.', 'Keem Bay, Achill Island, Co. Mayo', 'Car park above the beach; arrive before 11am on summer days.', array['Blue Flag', 'Lifeguarded (summer)', 'Cliff-ringed cove']),
  (12, 'Dog’s Bay & Gurteen Bay', 'Galway', 'beach', 53.3853, -9.9159, 'Free', '3 km around the headland', 'A tombolo of two white shell-sand beaches', 'Back-to-back beaches joined by a narrow spit near Roundstone, with turquoise water and sand made almost entirely of tiny fossilised shells. One of Connemara’s most striking coastal walks.', 'Dog’s Bay, Roundstone, Co. Galway', 'Free car parking behind both beaches.', array['Shell sand', 'Tombolo', 'Swimming & walking']),
  (13, 'Cobh Waterfront & Titanic Memorial', 'Cork', 'historic', 51.8505, -8.2951, 'Free', '2 km promenade walk', 'The Titanic’s last port of call', 'Walk the pastel harbour-front promenade where 123 passengers boarded the Titanic in 1912, its final stop before the Atlantic. The Lusitania Peace Memorial and cathedral views add to a town built on emigration history.', 'Cobh Promenade, Co. Cork', 'Free on-street parking around the town; paid car parks near the seafront.', array['Titanic’s last port', 'Heritage town', 'Harbour views']),
  (14, 'Slieve Gullion Passage Tomb', 'Armagh', 'viewpoint', 54.1180, -6.4361, 'Free', '1.5 km return from top car park', 'The highest surviving passage tomb in Ireland or Britain', 'Climb from the forest-drive car park to the Neolithic South Cairn on Armagh’s highest summit, with a small lake in the crater behind it and panoramic views over the Ring of Gullion.', 'Slieve Gullion Forest Park, Newry Road, Co. Armagh', 'Free car park at the top of the scenic forest drive.', array['576 m summit', 'Neolithic passage tomb', 'Ring of Gullion views']),
  (15, 'Trinity College Campus', 'Dublin', 'historic', 53.3438, -6.2546, 'Free (paid Book of Kells/Long Room)', 'Self-guided campus walk', 'Ireland’s oldest university, in the heart of the city', 'Wander cobbled squares dating to 1592, past the Campanile and the Rubrics to the Old Library building. The Long Room and Book of Kells need a ticket; the campus itself doesn’t.', 'Trinity College, College Green, Dublin 2', 'No on-site parking; use city-centre paid car parks or public transport.', array['Founded 1592', 'Free campus access', 'Paid Book of Kells']),
  (16, 'Benbulben View at Drumcliffe', 'Sligo', 'viewpoint', 54.3339, -8.5109, 'Free', 'Roadside stop', 'Yeats country, under Ireland’s iconic table mountain', 'Visit W.B. Yeats’s grave in Drumcliffe churchyard with Benbulben’s flat-topped silhouette rising behind it, the view that shaped his best-known epitaph.', 'Drumcliffe Church, Co. Sligo', 'Free car park at the church.', array['Yeats’s grave', 'Iconic mountain backdrop', '5 min stop']),
  (17, 'Hill of Tara', 'Meath', 'historic', 53.5766, -6.6106, 'Free', '2 km of walking paths', 'The ancient seat of Ireland’s High Kings', 'Walk the open grassy mounds of a royal and ceremonial site used for over 5,000 years, including the Stone of Destiny where High Kings were once crowned, with views across the Boyne Valley.', 'Hill of Tara, Co. Meath', 'Free car park at the visitor centre.', array['5,000+ years of use', 'Stone of Destiny', 'Open access']),

  -- ==================== HIDDEN GEMS (10) ====================
  (18, 'Glenbarrow Waterfall Loop', 'Laois', 'trail', 53.1538, -7.5391, 'Free', '7 km loop', 'A three-tiered waterfall hidden in the Slieve Bloom Mountains', 'Follow the River Barrow upstream through mature conifer woodland to Clamp Hole, where the water tumbles over three rocky tiers. The midlands hide some of Ireland’s quietest walking country, and this loop rarely sees a queue.', 'Glenbarrow car park, Rosenallis, Co. Laois', 'Free car park at the trailhead, signposted from Rosenallis village.', array['7 km loop', 'Moderate', 'Waymarked']),
  (19, 'Magho Viewpoint, Lough Navar Forest', 'Fermanagh', 'viewpoint', 54.4506, -7.9427, 'Free', '7 mile forest drive', 'A 300m clifftop panorama over Lower Lough Erne', 'Drive the Lough Navar Forest Drive to its highest point for a sweeping view across the lough’s scattered islands, stretching into Donegal, Sligo and Tyrone on a clear day.', 'Lough Navar Forest, Derrygonnelly, Co. Fermanagh', 'Free car park at the viewpoint, reached via the forest drive.', array['300 m high', 'Car-accessible', 'Picnic area']),
  (20, 'Lough Boora Discovery Park', 'Offaly', 'trail', 53.2333, -7.6167, 'Free', '2.8 km sculpture loop', 'A reclaimed bogland trail strung with large-scale sculpture', 'Follow the sculpture loop across former industrial cutaway bog, now a wetland sanctuary, passing two dozen artworks built from rail line, timber and stone.', 'Lough Boora Discovery Park, Kilcormac, Co. Offaly', 'Free car park, open 8am-6pm year-round.', array['2.8 km loop', 'Flat & accessible', 'Wildlife hide']),
  (21, 'Clare Glens', 'Limerick', 'trail', 52.6970, -8.3870, 'Free', '4 km loop', 'A red sandstone gorge of cascading waterfalls', 'Cross footbridges through mixed woodland as the Clare River drops through a series of falls on the Limerick-Tipperary border, one of the midlands’ best-kept walking secrets.', 'Clare Glens car park, Murroe, Co. Limerick', 'Free roadside car park beside the bridge, signposted from Murroe and Newport.', array['4 km loop', 'Easy-moderate', 'Picnic area']),
  (22, 'Murlough Beach', 'Down', 'beach', 54.2544, -5.9463, 'Free entry, paid car park', '4 mile strand', 'Four miles of dune-backed strand beneath the Mournes', 'Boardwalks cross a 6,000-year-old dune system to a long golden beach with the Mourne Mountains rising behind it, one of the finest coastal nature reserves in the north.', 'Murlough National Nature Reserve, Dundrum, Co. Down', 'National Trust car park, seasonal charge (roughly £3-£7); free for NT members.', array['4 mile strand', 'Dune trails', 'Blue Flag']),
  (23, 'Cavan Burren Park', 'Cavan', 'historic', 54.2119, -7.7194, 'Free', '3 km loop', 'A megalithic landscape of tombs and pre-bog walls', 'Wander a small, spiritual landscape of wedge and portal tombs, hut sites and stone-age field walls, overlooked by Cuilcagh Mountain, then follow the Cavan Way onward to the Shannon Pot, source of Ireland’s longest river.', 'Cavan Burren Park, Blacklion, Co. Cavan', 'Free car park with interpretive centre and picnic area.', array['5,000+ years old', '5 waymarked trails', 'Accessible path']),
  (24, 'Slieve Foye & Carlingford Lough Loop', 'Louth', 'viewpoint', 54.0486, -6.1889, 'Free', '9 km loop', 'A mountain loop above Ireland’s fjord-like lough', 'Climb from the medieval streets of Carlingford through forestry and open mountain to the 589m summit of Slieve Foye, with the lough, the Mournes and the Cooley Peninsula spread out below.', 'Carlingford Tourist Office car park, Co. Louth', 'Free car parking beside the harbour in Carlingford.', array['9 km loop', '589 m summit', 'Waymarked']),
  (25, 'Davagh Forest (OM Dark Sky Park)', 'Tyrone', 'camp', 54.7180, -6.9180, 'Free', '3.4 km Solar Walk', 'Stargazing and a Bronze Age stone circle complex', 'One of Ireland’s few designated Dark Sky Parks, in the foothills of the Sperrins. Follow the Solar Walk boardwalk from the observatory out to the Beaghmore Stone Circles, laid out by astronomers 4,000 years before this one existed.', 'Davagh Forest, Cookstown, Co. Tyrone', 'Free car parks (upper and lower) on site.', array['Dark Sky Park', '3.4 km Solar Walk', 'Bronze Age circles']),
  (26, 'Ballinesker Beach, Curracloe', 'Wexford', 'beach', 52.4028, -6.3597, 'Free', '8 mile strand', 'An eight-mile strand that stood in for Normandy', 'Steven Spielberg filmed the D-Day landing scenes of Saving Private Ryan on this vast stretch of dune-backed sand. On an ordinary day it’s simply one of the east coast’s best beaches for a long walk.', 'Curracloe Beach, Co. Wexford', 'Free car parks at Ballinesker, White Gap and Culletons Gap.', array['8 mile strand', 'Boardwalk access', 'Filming location']),
  (27, 'Woodstock Gardens & Forest Park', 'Kilkenny', 'trail', 52.5044, -7.0733, 'Free (small car-park charge near the gardens)', '3 km of trails', 'Victorian gardens and an ivy-covered avenue above the Nore', 'Wander terraced gardens, a noble fir avenue and woodland walks above the ruins of Woodstock House, with the River Nore and Inistioge village below.', 'Woodstock Gardens, Inistioge, Co. Kilkenny', 'Small free car park near the village bridge; paid car park at the main gardens entrance.', array['Victorian gardens', 'River views', 'Dawn-dusk'])
on conflict (id) do update set
  name = excluded.name,
  county = excluded.county,
  category = excluded.category,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  cost = excluded.cost,
  distance = excluded.distance,
  kicker = excluded.kicker,
  description = excluded.description,
  address = excluded.address,
  parking = excluded.parking,
  facts = excluded.facts;

select setval(
  pg_get_serial_sequence('public.locations', 'id'),
  greatest((select coalesce(max(id), 1) from public.locations), 1),
  true
);
