-- Wander Eire: up to three official gallery photos per location.
-- Run after photos-step.sql and security-step.sql. Safe to re-run.

create table if not exists public.location_photos (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete cascade,
  object_path text not null unique,
  position smallint not null check (position between 1 and 3),
  created_at timestamptz not null default now(),
  unique (location_id, position)
);

alter table public.location_photos enable row level security;

grant select on public.location_photos to anon, authenticated;
grant insert, delete on public.location_photos to authenticated;
grant usage, select on sequence public.location_photos_id_seq to authenticated;

drop policy if exists "Official location photos are readable" on public.location_photos;
create policy "Official location photos are readable" on public.location_photos
for select using (
  public.is_admin()
  or exists (
    select 1 from public.locations
    where locations.id = location_photos.location_id
      and locations.archived_at is null
  )
);

drop policy if exists "Admins can add official location photos" on public.location_photos;
create policy "Admins can add official location photos" on public.location_photos
for insert with check (public.is_admin());

drop policy if exists "Admins can delete official location photos" on public.location_photos;
create policy "Admins can delete official location photos" on public.location_photos
for delete using (public.is_admin());

drop policy if exists "Admins can upload official location photo files" on storage.objects;
create policy "Admins can upload official location photo files" on storage.objects
for insert to authenticated with check (
  bucket_id = 'location-photos'
  and (storage.foldername(name))[1] = 'official'
  and public.is_admin()
);

drop policy if exists "Official location photo files are readable" on storage.objects;
create policy "Official location photo files are readable" on storage.objects
for select using (
  bucket_id = 'location-photos'
  and exists (
    select 1
    from public.location_photos
    join public.locations on locations.id = location_photos.location_id
    where location_photos.object_path = name
      and (locations.archived_at is null or public.is_admin())
  )
);

drop policy if exists "Admins can delete official location photo files" on storage.objects;
create policy "Admins can delete official location photo files" on storage.objects
for delete to authenticated using (
  bucket_id = 'location-photos'
  and (storage.foldername(name))[1] = 'official'
  and public.is_admin()
);
