-- Wander Eire: private photo uploads with public access after approval.
-- Safe to re-run.

create table if not exists public.user_photos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  location_id bigint not null references public.locations(id) on delete cascade,
  object_path text not null unique,
  caption text check (caption is null or char_length(caption) <= 240),
  status public.contribution_status not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.user_photos enable row level security;

grant select on public.user_photos to anon, authenticated;
grant insert on public.user_photos to authenticated;
grant delete on public.user_photos to authenticated;
revoke update on public.user_photos from anon, authenticated;
grant update (status) on public.user_photos to authenticated;
grant usage, select on sequence public.user_photos_id_seq to authenticated;

drop policy if exists "Approved and owned photos are readable" on public.user_photos;
create policy "Approved and owned photos are readable" on public.user_photos
for select using (
  status = 'approved' or auth.uid() = user_id or public.is_admin()
);

drop policy if exists "Photos are attributable" on public.user_photos;
create policy "Photos are attributable" on public.user_photos
for insert with check (auth.uid() = user_id);

drop policy if exists "Owners can remove pending photos" on public.user_photos;
create policy "Owners can remove pending photos" on public.user_photos
for delete using (auth.uid() = user_id and status = 'pending');

drop policy if exists "Admins can moderate photos" on public.user_photos;
create policy "Admins can moderate photos" on public.user_photos
for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can delete photos" on public.user_photos;
create policy "Admins can delete photos" on public.user_photos
for delete using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'location-photos',
  'location-photos',
  false,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users can upload location photos" on storage.objects;
create policy "Users can upload location photos" on storage.objects
for insert to authenticated with check (
  bucket_id = 'location-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Approved and owned location photo files are readable" on storage.objects;
create policy "Approved and owned location photo files are readable" on storage.objects
for select using (
  bucket_id = 'location-photos'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin()
    or exists (
      select 1 from public.user_photos
      where object_path = name and status = 'approved'
    )
  )
);

drop policy if exists "Owners and admins can delete location photo files" on storage.objects;
create policy "Owners and admins can delete location photo files" on storage.objects
for delete to authenticated using (
  bucket_id = 'location-photos'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin()
  )
);
