create extension if not exists postgis;

create type public.location_category as enum ('trail', 'historic', 'viewpoint', 'beach', 'camp');
create type public.contribution_status as enum ('pending', 'approved', 'rejected');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table public.locations (
  id bigint generated by default as identity primary key,
  name text not null,
  county text not null,
  category public.location_category not null,
  latitude double precision not null,
  longitude double precision not null,
  cost text not null default 'Free',
  distance text,
  kicker text,
  description text,
  address text,
  parking text,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_ticks (
  user_id uuid references auth.users(id) on delete cascade,
  location_id bigint references public.locations(id) on delete cascade,
  ticked_at timestamptz not null default now(),
  primary key (user_id, location_id)
);

create table public.user_saves (
  user_id uuid references auth.users(id) on delete cascade,
  location_id bigint references public.locations(id) on delete cascade,
  saved_at timestamptz not null default now(),
  primary key (user_id, location_id)
);

create table public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  location_id bigint references public.locations(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  status public.contribution_status not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.locations enable row level security;
alter table public.user_ticks enable row level security;
alter table public.user_saves enable row level security;
alter table public.comments enable row level security;

create policy "Public locations are readable" on public.locations for select using (archived_at is null);
create policy "Profiles are self-readable" on public.profiles for select using (auth.uid() = id);
create policy "Profiles are self-editable" on public.profiles for update using (auth.uid() = id);
create policy "Ticks are owned" on public.user_ticks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Saves are owned" on public.user_saves for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Approved and owned comments are readable" on public.comments for select using (status = 'approved' or auth.uid() = user_id);
create policy "Comments are attributable" on public.comments for insert with check (auth.uid() = user_id and status = 'pending');

-- People may edit their display name, but never promote their own role.
revoke update on public.profiles from anon, authenticated;
grant update (display_name) on public.profiles to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)));
  return new;
end; $$;

create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
